<% if (ethereumNetwork != '"custom"') { %>network=<%- ethereumNetwork %>
<%}-%>
<% if (ethereumNetwork == '"custom"') { %>genesis-file=<%-customGenesisPath %>
<%}-%>

data-path=<%- dataPath ? dataPath : '~/besudata' %>

# JSON RPC configuration
rpc-http-enabled=<%- rpcHttpEnabled ? rpcHttpEnabled : false %>
<% if (rpcHttpEnabled) { %>rpc-http-host=<%- rpcHttpHost %>
rpc-http-port=<%= rpcHttpPort %>
rpc-http-apis=<%- rpcHttpApis %>
<%}-%>

# P2P configuration
p2p-enabled=<%- p2pEnabled ? p2pEnabled : false %>
<% if (p2pEnabled) { %>p2p-host=<%- p2pHost %>
p2p-port=<%= p2pPort %>
p2p-interface=<%- p2pInterface %>
discovery-enabled=<%= discoveryEnabled %>
<%}-%>

# GraphQL configuration
graphql-http-enabled=<%- graphqlHttpEnabled ? graphqlHttpEnabled : false %>
<% if (graphqlHttpEnabled) { %>graphql-http-host=<%- graphqlHttpHost %>
graphql-http-port=<%= graphqlHttpPort %>
<%}-%>

# Mining configuration
miner-enabled=<%- minerEnabled ? minerEnabled : false %>
<% if (minerEnabled) { %>miner-coinbase=<%-minerCoinbase %>
<%}-%>
